version: '3'

services:
  app:
    image: wordcannon/service
    restart: always
  web:
    image: wordcannon/web
    restart: always
    ports:
        - 8888:8888    

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always  
    ports:
      - 8080:8080    
